# Generated by Django 5.2.7 on 2025-11-04 05:36

import cargas_masivas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteConsultaMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Procesar'), ('PROCESADO', 'Procesado y Completado')], default='PENDIENTE', max_length=20)),
                ('archivo_subido', models.FileField(upload_to=cargas_masivas.models.ruta_archivo_subido)),
                ('archivo_resultado', models.FileField(blank=True, null=True, upload_to=cargas_masivas.models.ruta_archivo_resultado)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
