"""
Django settings for gestor_listas project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Hosts permitidos - leer desde .env (separados por coma)
# Ejemplo en .env: ALLOWED_HOSTS=midominio.com,localhost,127.0.0.1
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# Orígenes CSRF confiables - leer desde .env (separados por coma)
# Ejemplo en .env: CSRF_TRUSTED_ORIGINS=https://midominio.com
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='').split(',')
# Limpiar lista vacía si no hay orígenes configurados
CSRF_TRUSTED_ORIGINS = [origin for origin in CSRF_TRUSTED_ORIGINS if origin]



# Application definition

# APPS COMPARTIDAS (viven en el esquema 'public')
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Nuestras apps (todas juntas)
    'empresas',
    'usuarios',
    'consultas',
    'cargas_masivas.apps.CargasMasivasConfig',

    'core_admin',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestor_listas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestor_listas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




AUTH_USER_MODEL = 'usuarios.Usuario'


# --- CONFIGURACIÓN DE AUTENTICACIÓN ---

# URL a la que se redirigirá a los usuarios si intentan acceder a una página protegida sin estar logueados.
LOGIN_URL = '/cuentas/login/'

# URL a la que se redirigirá al usuario después de un inicio de sesión exitoso.
LOGIN_REDIRECT_URL = '/' # La página principal (nuestra página de búsqueda)

# URL a la que se redirigirá al usuario después de cerrar sesión.
LOGOUT_REDIRECT_URL = '/cuentas/login/' # Lo enviamos de vuelta a la página de login


# --- CREDENCIALES DEL API ---
API_TOKEN = config('API_TOKEN')
API_BASE_URL = config('API_BASE_URL')

# Tiempo de espera (segundos) por intento y número de intentos contra el
# webservice de listas (SIDIF / ConsultaListasPeps).
# Medido el 21 y 22-sep-2026: un ID con guion (NIT con dígito de verificación)
# tarda 48-60 s la PRIMERA vez que el proveedor lo ve, y <1 s después (lo deja
# en caché); sin guion responde en <1 s. Además hubo respuestas de 17-28 s de
# forma intermitente. Con 20 s los analistas veían "servicio no disponible".
# El techo lo pone el balanceador: corta a los 60 s (504). Por eso 55 s y un
# solo intento: es lo máximo que cabe. Cuando Advancit suba el idle timeout
# del ALB a 120 s, poner API_TIMEOUT=90 en el .env de cada cliente.
# Solo se reintenta ante timeout o error de conexión; un error de aplicación
# del proveedor (MensajeError, HTTP 500) no se reintenta porque gastaría cupo.
# Peor caso = API_REINTENTOS x API_TIMEOUT + 1 s de pausa entre intentos.
API_TIMEOUT = config('API_TIMEOUT', default=55, cast=int)
API_REINTENTOS = config('API_REINTENTOS', default=1, cast=int)


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


# --- CONFIGURACIÓN DE CORREO (Producción) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Estas dos líneas son las más importantes (basado en el puerto 465)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)

# Estos no cambian
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER # El correo saliente será 'info@vadomdata.com'
ADMIN_EMAIL = config('ADMIN_EMAIL', default='vadomdata@gmail.com')

MI_DOMINIO = config('MI_DOMINIO', default='http://127.0.0.1:8000')

# Notificar por email a los superiores de la empresa cuando una búsqueda
# encuentra hallazgos. Configurable por cliente desde el .env.
NOTIFICAR_HALLAZGOS = config('NOTIFICAR_HALLAZGOS', default=True, cast=bool)

# Aviso por email cuando una empresa supera su cupo mensual de consultas.
NOTIFICAR_EXCESO_CUPO = config('NOTIFICAR_EXCESO_CUPO', default=True, cast=bool)
# Correo que recibe esos avisos (por defecto, el ADMIN_EMAIL).
EMAIL_ALERTA_CUPO = config('EMAIL_ALERTA_CUPO', default=ADMIN_EMAIL)

# --- Procesos judiciales (Rama Judicial / CPNU) ------------------------------
# Consulta complementaria a las listas restrictivas: procesos judiciales del
# nombre consultado. Es INFORMATIVA (la Rama solo busca por nombre y no devuelve
# documento, así que puede traer homónimos) y nunca bloquea la búsqueda LAFT.
# Interruptor TOTAL por cliente: en False no se consulta la Rama, la URL del
# detalle devuelve 404 y la sección desaparece de la ficha y del PDF (aunque la
# búsqueda tenga procesos guardados de cuando estuvo activa; los datos no se
# borran, solo dejan de mostrarse). Default False: cada cliente se enciende
# explícitamente desde su .env cuando se decida activarle la feature.
CONSULTAR_PROCESOS_JUDICIALES = config('CONSULTAR_PROCESOS_JUDICIALES', default=False, cast=bool)

# La API vive en el puerto 448 (el 443 sirve la SPA del portal, no la API).
CPNU_BASE_URL = config(
    'CPNU_BASE_URL',
    default='https://consultaprocesos.ramajudicial.gov.co:448/api/v2',
)
# Esta consulta ocurre dentro de la petición del analista: el peor caso (Rama
# caída) es CPNU_REINTENTOS x CPNU_TIMEOUT + las esperas del backoff.
CPNU_TIMEOUT = config('CPNU_TIMEOUT', default=15, cast=int)
CPNU_REINTENTOS = config('CPNU_REINTENTOS', default=2, cast=int)
# Páginas de 20 procesos. Con 5 se traen máximo 100; si el nombre tiene más,
# se guarda el total que reporta la Rama y la ficha avisa "mostrando X de Y".
CPNU_MAX_PAGINAS = config('CPNU_MAX_PAGINAS', default=5, cast=int)


# ===========================================
# CONFIGURACIÓN HÍBRIDA DE ARCHIVOS ESTÁTICOS Y MEDIA
# ===========================================
# - DEBUG=True  → Almacenamiento LOCAL (desarrollo)
# - DEBUG=False → Almacenamiento S3 (producción)

# Rutas locales (siempre necesarias)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

if DEBUG:
    # ===========================================
    # MODO DESARROLLO (LOCAL)
    # ===========================================
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'

    # Usar almacenamiento local por defecto
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

else:
    # ===========================================
    # MODO PRODUCCIÓN (AWS S3)
    # ===========================================

    # Configuración de AWS S3
    AWS_STORAGE_BUCKET_NAME = 'vadomdata'
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None  # Evita error "AccessControlListNotSupported"

    # Prefijo dinámico por cliente (ej: 'comertex', 'redpapaz')
    S3_PREFIX = config('S3_CLIENT_PREFIX', default='default_prefix')

    # Importar backend de S3
    from storages.backends.s3boto3 import S3Boto3Storage

    # Clases de almacenamiento personalizadas
    class StaticStorage(S3Boto3Storage):
        location = f'{S3_PREFIX}/static'

    class MediaStorage(S3Boto3Storage):
        location = f'{S3_PREFIX}/media'
        file_overwrite = False

    # URLs apuntando a S3
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{S3_PREFIX}/static/'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{S3_PREFIX}/media/'

    # Asignar backends de S3
    STORAGES = {
        "default": {
            "BACKEND": "gestor_listas.settings.MediaStorage",
        },
        "staticfiles": {
            "BACKEND": "gestor_listas.settings.StaticStorage",
        },
    }


# --- REGISTRO DE ERRORES ---------------------------------------------------
# Sin esto, con DEBUG=False Django NO escribe los tracebacks en ningún lado
# (su configuración interna solo los manda a consola si DEBUG=True, o por
# correo a ADMINS). Resultado: un error 500 en producción no deja rastro.
# Aquí los mandamos a stderr, que mod_wsgi redirige al ErrorLog de Apache
# del cliente (/var/log/apache2/<cliente>_error.log).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'detallado': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'consola': {
            'class': 'logging.StreamHandler',   # stderr -> ErrorLog de Apache
            'formatter': 'detallado',
        },
    },
    'root': {
        'handlers': ['consola'],
        'level': 'WARNING',
    },
    'loggers': {
        # Tracebacks de las peticiones que fallan (error 500)
        'django.request': {
            'handlers': ['consola'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Nuestro propio código (services.py, notifications.py, ...)
        'consultas': {
            'handlers': ['consola'],
            'level': 'INFO',
            'propagate': False,
        },
        'cargas_masivas': {
            'handlers': ['consola'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
